apiVersion: v1
kind: Pod
metadata:
  name: k8sapideploy-back
  namespace: k8sapideploy
  labels:
    app: k8sapi
spec:
  containers:
    - name: k8sapideploy-back-prod
      image: wylath/k8sapideployback:002
      resources:
        limits:
          memory: "200Mi"
          cpu: "0.5"
        requests:
          memory: "1Mi"
          cpu: "0.5"
      ports:
      - containerPort: 3000 
  nodeName: kind-worker