apiVersion: v1
kind: Pod
metadata:
  name: k8sapideploy-db
  namespace: k8sapideploy
  labels:
    app: k8sapidb
spec:
  nodeName: kind-worker
  replicas: 5
  template:
    metadata:
      labels:
        app: k8sapidb
    spec:
      containers:
        - name: k8sapideploy-db-prod
          image: wylath/k8sapideploydb:001
          resources:
            limits:
              memory: "600Mi"
              cpu: "0.5"
            requests:
              memory: "1Mi"
              cpu: "0.5"
          ports:
          - containerPort: 5432