apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sapidb
  namespace: k8sapideploy
  labels:
    app: k8sapidb
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8sapidb
  template:
    metadata:
      labels:
        app: k8sapidb
    spec:
      containers:
        - name: postgres
          image: wylath/k8sapideploydb:002
          resources:
            limits:
              memory: "600Mi"
              cpu: "0.5"
            requests:
              memory: "1Mi"
              cpu: "0.5"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret